baseURL: https://aasthakamra-portfolio.netlify.app/
languageCode: en-us
title: Portfolio website for Aastha Kamra
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      A RESPONSIVE SITE TEMPLATE DESIGNED BY HTML5 UP
      AND RELEASED UNDER THE CREATIVE COMMONS.
    title: Hi, my name is Aastha
  blog: {}
  contact:
    address:
      - city: London
        country: United Kingdom
        street: Bishops Bridge Road
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: akamra.mba2024@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (+44) 7949987316
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: AKProductions
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-twitter
        label: Twitter
        url: https://twitter.com/KamraAastha
      - icon: #
        label: #
        url: #
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/aastha.kamra/?hl=en
      - icon: fa-github
        label: GitHub
        url: https://github.com/aasthakamra
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/aasthakamra/?originalSubdomain=in
  image: ''
  name: Aastha Kamra
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Education and Experience
        url: '#'
      - name: Blogs and Publications
        url: blogs
      - name: #
        url: #
      - name: #
        url: #
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: pic01.jpg
        subtitle: Analysing daily and monthly returns of djia stocks to ascertain the risk-return tradeoff
        title: Data Manipulation
        url: blogs/aliquam
      - image: pic02.jpg
        subtitle: Visualizing data from party donations over time, and scraping foreign contributions
        title: Data Visualization
        url: blogs/tempus
      - image: pic03.jpg
        subtitle: Predicting Bedechel Test Results modelling women's representation in hollywood films
        title: Machine Learning
        url: blogs/magna
      - image: pic04.jpg
        subtitle: Mapping city and merchant locations to predict fraudulent credit card transactions
        title: Ipsum
        url: blogs/ipsum
      - image: #
        subtitle: #
        title: #
        url: blogs/ipsum
      - image: #
        subtitle: #
        title: Etiam
        url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Aastha is a driven professional with a background in economics coupled with extensive experience in management consulting and early-stage investing. She is currently pursuing her MBA at London Business School. Previously, she has worked at Omidyar Network India, where she played a key role in deal sourcing, due diligence, and portfolio management for the $465M fund. Prior to that, Aastha worked at Bain & Company, where she advised leading consumer goods clients across Europe and Asia on brand strategy and growth acceleration. Aastha is an enthusiastic data science practitioner who strives to integrate her knowledge of data manipulation, analysis and visualization to drive data-driven decision-making for the organiations she works with."
    title: Overview
    url: blogs
markup: 
  goldmark: 
    renderer: 
      unsafe: true